routes/web.php
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
    Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

    Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
    Route::get('password/reset/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::get('password/reset/email', 'Auth\ForgotPasswordController@resetEmail')->name('password.reset.email');
    Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset/request', 'Auth\ForgotPasswordController@resetRequest')->name('password.reset.request');

    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    Route::get('verify/email', 'Auth\RegisterController@email')->name('email.verification');
    Route::get('verify/email/{token}', 'Auth\RegisterController@verifyEmail')->name('verify.email');
    Route::get('verify/email/resend', 'Auth\RegisterController@resendEmailShow')->name('resend.email.show');
    Route::post('verify/email/resend', 'Auth\RegisterController@resendEmail')->name('resend.email.verification');
    Route::get('verify/phone', 'Auth\RegisterController@phone')->name('phone.verification');
    Route::post('verify/phone', 'Auth\RegisterController@verifyPhone')->name('verify.phone');
    Route::get('verify/phone/resend', 'Auth\RegisterController@resendPhoneShow')->name('resend.phone.show');
    Route::post('verify/phone/resend', 'Auth\RegisterController@resendPhone')->name('resend.phone.verification');

    Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'User'], function () {
        Route::get('add-email', 'ProfileController@addEmailShow')->name('add-email-show');
        Route::get('add-phone', 'ProfileController@addPhoneShow')->name('add-phone-show');
        Route::post('add-email', 'ProfileController@addEmail')->name('add-email');
        Route::post('add-phone', 'ProfileController@addPhone')->name('add-phone');
        Route::get('verify/email', 'ProfileController@email')->name('email.verification');
        Route::get('verify/phone', 'ProfileController@phone')->name('phone.verification');
        Route::get('verify/email/{token}', 'ProfileController@verifyEmail')->name('verify.email');
        Route::post('verify/phone', 'ProfileController@verifyPhone')->name('verify.phone');
        Route::post('add-inform', 'ProfileController@update')->name('add-inform');

        Route::post('request-manager-role', 'ProfileController@requestManagerRole')->name('manager.request');

        Route::get('add-photo', 'ProfileController@addPhoto')->name('add-photo');

        Route::get('change-password', 'ProfileController@changePasswordPage')->name('change-password');
        Route::post('change-password', 'ProfileController@changePassword')->name('change-password');
    });

    Route::get('home', 'HomeController@index')->name('home');
    Route::get('', 'HomeController@index')->name('front-home');

    Route::get('search', 'SearchResultsController@searchResults')->name('search');
    Route::get('search-product-filter', 'SearchResultsController@SearchFilter')->name('search-product-filter');


    Route::get('auth', 'AuthController@auth')->name('auth');
    Route::get('mail', 'MailController@mail')->name('mail');
    Route::get('sms', 'SmsController@sms')->name('sms');

    Route::get('blogs', 'BlogController@blogs')->name('blogs');
    Route::get('blogs/{blog}', 'BlogController@show')->name('blogs.show');
    Route::get('brands', 'BrandsController@brands')->name('brands');
    Route::get('brands/{brand}', 'BrandsController@show')->name('brands.show');

    Route::get('cart', 'CartController@cart')->name('cart');
    Route::get('checkout', 'CheckoutController@checkout')->name('checkout');
    Route::post('pay', 'PayController@pay')->name('pay');
    Route::post('finalStep', 'PayController@finalStep')->name('finalStep');
    Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], function () {
        Route::get('', 'CatalogController@catalog')->name('list');
    });
    Route::get('catalogsection', 'CategoryController@index')->name('catalogsection');

    Route::get('/delivery', 'DeliveryGuarantyPaymentController@deliveryGuarantyPayment')->name('delivery'); // delivery, guaranty, payment are combined
    Route::get('popular', 'PopularController@popular')->name('popular');

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('show/{product}', 'ProductController@show')->name('show');
        Route::post('{product}/add-review', 'ProductController@addReview')->name('add-review');
        Route::group(['prefix' => '{product}/cart', 'as' => 'cart.'], function () {
            Route::get('add', 'ProductController@addToCart')->name('add');
            Route::patch('update-cart', 'ProductController@update')->name('update');
            Route::delete('remove-from-cart', 'ProductController@remove')->name('remove');
        });
        Route::get('{product}/compare-with/{comparingProduct}', 'ProductController@compare')->name('compare');
        Route::get('new-products', 'ProductController@newProducts')->name('new-products');
    });

    Route::get('add-to-cart/{id}', 'ProductController@addToCart')->name('addCard');
    Route::patch('update-cart', 'ProductController@update');
    Route::delete('remove-from-cart', 'ProductController@remove');

    Route::group(['prefix' => 'discounts', 'as' => 'discounts.'], function () {
        Route::get('', 'DiscountController@index')->name('index');
        Route::get('/{discount}', 'DiscountController@show')->name('show');
    });

    Route::group(['prefix' => 'shops', 'as' => 'shops.'], function () {
        Route::get('', 'ShopsController@index')->name('index');
        Route::get('{store}', 'ShopsController@view')->name('show');
    });


    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::get('/{products_path?}', 'CategoryController@show')->name('show')->where('products_path', '.+');
//        Route::get('{category}', 'CategoryController@show')->name('show');
    });

    Route::resource('/videos', 'VideosController');

    Route::group(['as' => 'user.','namespace' => 'User'], function () {
            Route::get('setting','ProfileController@index')->name('setting');
            Route::get('profile','ProfileController@show')->name('profile');
            Route::put('setting','ProfileController@update')->name('update');
            Route::get('favorites','FavoriteController@favorites')->name('favorites')->middleware('auth');
            Route::get('add-to-favorite/{product}','FavoriteController@addToFavorite')->name('favorites.add');
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/{page_path}', 'PageController@show')->name('show')->where('page_path', '.+');
    });

    Route::group(['prefix' => 'stores', 'as' => 'stores.'], function () {
        Route::get('', 'StoresController@index')->name('index');
        Route::get('{store}', 'StoresController@store')->name('show');
        Route::get('view/{store}', 'StoresController@view')->name('view');
        Route::get('stores', 'StoresController@view')->name('store');
    });

    Route::get('cart-list', 'CartController@index')->name('cart');
    Route::get('cart-header', 'CartController@showHeader');

    Route::get('compare', 'CompareController@compare')->name('compare');

});

//--------------- Dashboard ------------------//
Route::group(['prefix' => 'ru','name' => '','middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']],function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'can:admin-panel']], function () {
        Route::group(['prefix' => 'blog', 'as' => 'blog.', 'namespace' => 'Blog'], function () {
            Route::resource('videos', 'VideoController');
            Route::group(['prefix' => 'videos/{video}', 'as' => 'videos.'], function () {
                Route::post('remove-poster', 'VideoController@removePoster')->name('remove-poster');
                Route::post('remove-video', 'VideoController@removeVideo')->name('remove-video');
                Route::post('publish', 'VideoController@publish')->name('publish');
                Route::post('discard', 'VideoController@discard')->name('discard');
            });

            Route::resource('posts', 'PostController');
            Route::group(['prefix' => 'posts/{post}', 'as' => 'posts.'], function () {
                Route::post('remove-file', 'PostController@removeFile')->name('remove-file');
                Route::post('publish', 'PostController@publish')->name('publish');
                Route::post('discard', 'PostController@discard')->name('discard');
            });
        });

        Route::resource('banners', 'BannerController');
        Route::group(['prefix' => 'banners/{banner}', 'as' => 'banners.'], function () {
            Route::post('remove-file', 'BannerController@removeFile')->name('remove-file');
            Route::post('publish', 'BannerController@publish')->name('publish');
            Route::post('discard', 'BannerController@discard')->name('discard');
        });

        Route::resource('sliders', 'SlidersController');
        Route::group(['prefix' => 'sliders/{slider}', 'as' => 'sliders.'], function () {
            Route::post('first', 'SlidersController@first')->name('first');
            Route::post('up', 'SlidersController@up')->name('up');

app/Http/Controllers/Api/SearchController.php
<?php


namespace App\Http\Controllers\Api;


use App\Entity\Brand;
use App\Entity\Category;
use App\Entity\Shop\Product;
use App\Entity\Store;
use App\Helpers\PaginateHelper;
use App\Http\Resources\BrandResource;
use App\Http\Resources\Shop\ProductResource;
use App\Http\Resources\StoreResource;
use Illuminate\Http\Request;

class SearchController
{
    public function search(Request $request)
    {
        if (!empty($value = $request->get('search'))) {
            $categoryId = $request->get('category_id');
            $arrayProducts = collect();

            $length = 10;
            $productCategoryIds = [];
            if ($categoryId !== "all"){
                $getCategories = Category::where('id', $categoryId)->first();
                $getCategories = $getCategories->children()->get();

                foreach ($getCategories as $i => $category){
                    $productCategoryIds[$i] = $category->id;
                }
            }
            if ($categoryId && $categoryId !== "all") {
                $products = Product::search($value)->where('status', Product::STATUS_ACTIVE)
                    ->get();
                $products = $products->whereIn('main_category_id', $productCategoryIds)->take(10);

            } else {
                $products = Product::search($value)->where('status', Product::STATUS_ACTIVE)->paginate(10);
//                dd($products);
            }
            ProductResource::collection($products);

            $products->each(function ($product) use ($arrayProducts) {
                $arrayProducts->push($product);
            });
            if (($length -= $arrayProducts->count()) <= 0) {
                return response()->json([
                    'products' => $arrayProducts->toArray(),
                    'brands' => null,
                    'stores' => null,
                ]);
            }

//            if ($categoryId) {
//                $brands = Brand::search($value)->where('categories', $categoryId)->paginate($length);
//            } else {
                $brands = Brand::search($value)->paginate($length);
//            }
            BrandResource::collection($brands);
            if (($length -= $brands->count()) <= 0) {
                return response()->json([
                    'products' => $arrayProducts->toArray(),
                    'brands' => $brands->toArray(),
                    'stores' => null,
                ]);
            }

//            if ($categoryId) {
//                $stores = Store::search($value)->where('status', Store::STATUS_ACTIVE)
//                    ->where('categories', $categoryId)->paginate($length);
//            } else {
                $stores = Store::search($value)->where('status', Store::STATUS_ACTIVE)->paginate($length);
//            }
            StoreResource::collection($stores);
            return response()->json([
                'products' => $arrayProducts->toArray(),
                'brands' => $brands->toArray(),
                'stores' => $stores->toArray(),
            ]);
        }

        return [];
    }
}

resources/views/search/search-results.blade.php
@extends('layouts.app')

@section('title', trans('frontend.breadcrumb.search'))

{{--@include ('includes.common-style')--}}

@section('styles')
    {{-- <link rel="stylesheet" href="{{asset('css/blog-news.css')}}"> --}}
@endsection

@section('body')

    <!-- products-brands-shops-blogs-video btn -->
    @include('layouts.products-brands-shops-videos-btn')

    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-products" role="tabpanel" aria-labelledby="pills-products-tab">
            <!-- products body -->
            <div class="outter-catalog-view">
                <!-- big filter without title checkbox -->
                @if(!$products->isEmpty())
                    @include('search.sidebar', ['sidebar_is' => 'products'])
                @endif

                <div class="wrapper-filtered-items">

                    <h6>
                        {!! trans('frontend.number_found_product', ['query' => session('search'), 'result' => !$products->isEmpty() ? count($products->items()) : 0, 'category' => count($categories)])  !!}
                    </h6>
                    @if(!$products->isEmpty())
                        <nav class=" navbar navbar-expand-custom sort-types">
                            <!--sort-by options  -->
                        @include('layouts.sort-by-options')

                        <!-- small filter without title checkbox -->

                            @include('filters.small-filter-with-title-checkbox')
                        </nav>
                    @endif

                <!-- list mosaic catalog items -->
                    @include('layouts.products-list-grid')

                <!-- pagination -->
                    @include('layouts.pagination')

                </div>
            </div>
        </div>
        <div class="tab-pane fade show" id="pills-brands" role="tabpanel" aria-labelledby="pills-brands-tab">
            <!-- brands body -->
            <div class="outter-catalog-view">
                <!-- big filter without title checkbox -->
                @if(!$products->isEmpty())
                    @include('search.sidebar', ['sidebar_is' => 'Brands', 'categories' => $brandsCategory])
                @endif

                <div class="wrapper-filtered-items">

                    <h6>
                        {!! trans('frontend.number_found_product', ['query' => session('search'), 'result' => !$brandFilter->isEmpty() ? count($brandFilter) : 0, 'category' => count($brandFilter)])  !!}
                    </h6>

                    <div class="brands-by-letter row w-100 mt-4">
                        @foreach($brandFilter as $brand)
                            <div class="row col-2">
                                <div class="col-8 h-75 align-items-center d-flex">
                                    <a href="brands/{{$brand->id}}"><img src="{{ $brand->logoOriginal }}" alt="" class="img-thumbnail w-auto"></a>
                                </div>
                                <div class="col-8"><a href="brands/{{$brand->id}}" class="d-block mt-2">{{ $brand->name }}</a></div>
                            </div>
                        @endforeach
                    </div>

                    <!-- list mosaic catalog items -->
{{--                    @include('brand.brands', )--}}
{{--                                        @include('layouts.list-mosaic-catalog-items', ['products'=>$products])--}}

                </div>
            </div>
        </div>
        <div class="tab-pane fade show" id="pills-shops" role="tabpanel" aria-labelledby="pills-shops-tab">
            <!-- shops body -->
            <div class="outter-list-of-shops">
                <!-- big filter without title checkbox -->
                @if(!$stores->isEmpty())
                    @include('search.sidebar', ['sidebar_is' => 'Brands', 'categories' => $storesCategory])
                @endif

                <div class="wrapper-filtered-items">

                    <h6>
                        {!! trans('frontend.number_found_product', ['query' => session('search'), 'result' => !$stores->isEmpty() ? count($stores->items()) : 0, 'category' => count($storesCategory)])  !!}
                    </h6>

                    <!-- shop items -->
                    @include('stores.storesList')

                </div>
            </div>

        </div>
        <div class="tab-pane fade show" id="pills-blogs" role="tabpanel" aria-labelledby="pills-blogs-tab">
            <!-- blogs body -->
            <div class="outter-catalog-view">
                <!-- big filter without title checkbox -->
                @if(!$blogs->isEmpty())
                    @include('search.sidebar', ['sidebar_is' => 'Brands', 'categories' => $blogsCategory])
                @endif

                <div class="wrapper-filtered-items">

                    <h6>
                        {!! trans('frontend.number_found_product', ['query' => session('search'), 'result' => !$blogs->isEmpty() ? count($blogs->items()) : 0, 'category' => count($blogsCategory)])  !!}
                    </h6>

                    <!-- blog items -->
                    <div class="all-filtered-blogs">
                        @foreach($blogs as $blog)
                            <a href="{{ route('blogs.show', $blog) }}">
                                <div class="blog-item">
                                    <div class="image">
                                        <img src="{{$blog->fileOriginal}}" alt="">
                                        <div class="image-overlay"></div>
                                    </div>
                                    <div class="description">
                                        <h6 class="title">{{$blog->title}}</h6>
                                        <p>{{$blog->description}}</p>
                                    </div>
                                </div>
                            </a>
                        @endforeach
                        {{ $blogs->links() }}
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade show" id="pills-videos" role="tabpanel" aria-labelledby="pills-videos-tab">
            <!-- videos body -->
            <div class="outter-list-of-videos">
                <!-- big filter without title checkbox -->
                @if(!$blogs->isEmpty())
                    @include('search.sidebar', ['sidebar_is' => 'Brands', 'categories' => $videosCategory])
                @endif

                <div class="wrapper-filtered-videos">

                    <h6>
                        {!! trans('frontend.number_found_product', ['query' => session('search'), 'result' => !$videos->isEmpty() ? count($videos->items()) : 0, 'category' => count($videosCategory)])  !!}
                    </h6>

                    <div class="all-filtered-videos">
                        @foreach($videos as $video)
                            <a href="{{ route('videos.show', $video) }}">
                                <div class="video-item">
                                    <img src="{{$video->posterThumbnail}}" alt="" class="poster">
                                    <div class="video-overlay">
                                        <h6>{{$video->title}}</h6>
                                        <button class="btn play">
                                            <div class="arrow-right"></div>
                                        </button>
                                    </div>
                                </div>
                            </a>
                        @endforeach
                    </div>


                </div>
            </div>
        </div>
        <div>

            <!-- NEWS LETTER -->
            @if(isset($newProducts))
                @include ('layouts.carousel-products',
['products' => $newProducts, "title" => trans('frontend.novelty_upper'), 'rate_for' => ['js' => '"N"', 'html' => 'N']])
            @endif
            @endsection

            @section('script')
                <script src="{{mix('js/2-catalog-page.js', 'build')}}"></script>
                <script src="{{asset('js/jquery.rateyo.js')}}"></script>
                <script src="{{asset('js/range-slider.js')}}"></script>

            @push('script')
                    <script>
                        $(function () {
                            let min_price = {{$min_price}}, max_price = {{$max_price}}
                            var $range = $(".js-range-slider"),
                                $inputFrom = $(".js-input-from"),
                                $inputTo = $(".js-input-to"),
                                instance,
                                min = min_price,
                                max = max_price,
                                from = 0,
                                to = 0;

                            $range.ionRangeSlider({
                                type: "double",
                                min: min,
                                max: max,
                                from: min_price,
                                to: max_price,
                                prefix: '',
                                onStart: updateInputs,
                                onChange: updateInputs,
                                step: 100,
                                prettify_enabled: true,
                                prettify_separator: ".",
                                values_separator: " - ",
                                force_edges: true,


                            });

                            instance = $range.data("ionRangeSlider");

                            function updateInputs (data) {
                                from = data.from;
                                to = data.to;

                                $inputFrom.prop("value", from);
                                $inputTo.prop("value", to);
                            }

                            $inputFrom.on("input", function () {
                                var val = $(this).prop("value");

                                // validate
                                if (val < min) {
                                    val = min;
                                } else if (val > to) {
                                    val = to;
                                }

                                instance.update({
                                    from: val
                                });
                            });

                            $inputTo.on("input", function () {
                                var val = $(this).prop("value");

                                // validate
                                if (val < from) {
                                    val = from;
                                } else if (val > max) {
                                    val = max;
                                }

                                instance.update({
                                    to: val
                                });
                            });

                        });

                    </script>
    @endpush
@endsection

resources/views/search/sidebar.blade.php
<form action="/search-product-filter" class="big-filter-without-title-checkbox" id="shop-filter-form" method="GET">
{{--    {{ $sidebar_is }} type of sidebar --}}
    <input type="hidden" name="search" value="{{ session()->has('search') ? session('search') : '' }}">
    @if($sidebar_is != 'Brands')
        @include('filters.brand-filter')

    @endif

    @include('filters.category-filter')

    @if($sidebar_is != 'Brands')
        @include('filters.price-filter')
    @endif
    <input type="submit" id="catalog-filter-button" value="{{ trans('frontend.apply_filter') }}">
    <input type="hidden" name="order_by" id="sort-hidden-input">
</form>