routes/web.php
    Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
    Route::get('password/reset/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::get('password/reset/email', 'Auth\ForgotPasswordController@resetEmail')->name('password.reset.email');
    Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset/request', 'Auth\ForgotPasswordController@resetRequest')->name('password.reset.request');

    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    Route::get('verify/email', 'Auth\RegisterController@email')->name('email.verification');
    Route::get('verify/email/{token}', 'Auth\RegisterController@verifyEmail')->name('verify.email');
    Route::get('verify/email/resend', 'Auth\RegisterController@resendEmailShow')->name('resend.email.show');
    Route::post('verify/email/resend', 'Auth\RegisterController@resendEmail')->name('resend.email.verification');
    Route::get('verify/phone', 'Auth\RegisterController@phone')->name('phone.verification');
    Route::post('verify/phone', 'Auth\RegisterController@verifyPhone')->name('verify.phone');
    Route::get('verify/phone/resend', 'Auth\RegisterController@resendPhoneShow')->name('resend.phone.show');
    Route::post('verify/phone/resend', 'Auth\RegisterController@resendPhone')->name('resend.phone.verification');

    Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'User'], function () {
        Route::get('add-email', 'ProfileController@addEmailShow')->name('add-email-show');
        Route::get('add-phone', 'ProfileController@addPhoneShow')->name('add-phone-show');
        Route::post('add-email', 'ProfileController@addEmail')->name('add-email');
        Route::post('add-phone', 'ProfileController@addPhone')->name('add-phone');
        Route::get('verify/email', 'ProfileController@email')->name('email.verification');
        Route::get('verify/phone', 'ProfileController@phone')->name('phone.verification');
        Route::get('verify/email/{token}', 'ProfileController@verifyEmail')->name('verify.email');
        Route::post('verify/phone', 'ProfileController@verifyPhone')->name('verify.phone');
        Route::post('add-inform', 'ProfileController@update')->name('add-inform');

        Route::post('request-manager-role', 'ProfileController@requestManagerRole')->name('manager.request');

        Route::get('add-photo', 'ProfileController@addPhoto')->name('add-photo');

        Route::get('change-password', 'ProfileController@changePasswordPage')->name('change-password');
        Route::post('change-password', 'ProfileController@changePassword')->name('change-password');
    });

    Route::get('home', 'HomeController@index')->name('home');
    Route::get('', 'HomeController@index')->name('front-home');

    Route::get('search', 'SearchResultsController@searchResults')->name('search');
    Route::get('search-product-filter', 'SearchResultsController@SearchFilter')->name('search-product-filter');


    Route::get('auth', 'AuthController@auth')->name('auth');
    Route::get('mail', 'MailController@mail')->name('mail');
    Route::get('sms', 'SmsController@sms')->name('sms');

    Route::get('blogs', 'BlogController@blogs')->name('blogs');
    Route::get('blogs/{blog}', 'BlogController@show')->name('blogs.show');
    Route::get('brands', 'BrandsController@brands')->name('brands');
    Route::get('brands/{brand}', 'BrandsController@show')->name('brands.show');

    Route::get('cart', 'CartController@cart')->name('cart');
    Route::get('checkout', 'CheckoutController@checkout')->name('checkout');
    Route::post('pay', 'PayController@pay')->name('pay');
    Route::post('finalStep', 'PayController@finalStep')->name('finalStep');
    Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], function () {
        Route::get('', 'CatalogController@catalog')->name('list');
    });
    Route::get('catalogsection', 'CategoryController@index')->name('catalogsection');

    Route::get('/delivery', 'DeliveryGuarantyPaymentController@deliveryGuarantyPayment')->name('delivery'); // delivery, guaranty, payment are combined
    Route::get('popular', 'PopularController@popular')->name('popular');

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('show/{product}', 'ProductController@show')->name('show');
        Route::post('{product}/add-review', 'ProductController@addReview')->name('add-review');
        Route::group(['prefix' => '{product}/cart', 'as' => 'cart.'], function () {
            Route::get('add', 'ProductController@addToCart')->name('add');
            Route::patch('update-cart', 'ProductController@update')->name('update');
            Route::delete('remove-from-cart', 'ProductController@remove')->name('remove');
        });
        Route::get('{product}/compare-with/{comparingProduct}', 'ProductController@compare')->name('compare');
        Route::get('new-products', 'ProductController@newProducts')->name('new-products');
    });

    Route::get('add-to-cart/{id}', 'ProductController@addToCart')->name('addCard');
    Route::patch('update-cart', 'ProductController@update');
    Route::delete('remove-from-cart', 'ProductController@remove');

    Route::group(['prefix' => 'discounts', 'as' => 'discounts.'], function () {
        Route::get('', 'DiscountController@index')->name('index');
        Route::get('/{discount}', 'DiscountController@show')->name('show');
    });

    Route::group(['prefix' => 'shops', 'as' => 'shops.'], function () {
        Route::get('', 'ShopsController@index')->name('index');
        Route::get('{store}', 'ShopsController@view')->name('show');
    });


    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::get('/{products_path?}', 'CategoryController@show')->name('show')->where('products_path', '.+');
//        Route::get('{category}', 'CategoryController@show')->name('show');
    });

    Route::resource('/videos', 'VideosController');

    Route::group(['as' => 'user.','namespace' => 'User'], function () {
            Route::get('setting','ProfileController@index')->name('setting');
            Route::get('profile','ProfileController@show')->name('profile');
            Route::put('setting','ProfileController@update')->name('update');
            Route::get('favorites','FavoriteController@favorites')->name('favorites')->middleware('auth');
            Route::get('add-to-favorite/{product}','FavoriteController@addToFavorite')->name('favorites.add');
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/{page_path}', 'PageController@show')->name('show')->where('page_path', '.+');
    });

    Route::group(['prefix' => 'stores', 'as' => 'stores.'], function () {
        Route::get('', 'StoresController@index')->name('index');
        Route::get('{store}', 'StoresController@store')->name('show');
        Route::get('view/{store}', 'StoresController@view')->name('view');
        Route::get('stores', 'StoresController@view')->name('store');
    });

    Route::get('cart-list', 'CartController@index')->name('cart');
    Route::get('cart-header', 'CartController@showHeader');

    Route::get('compare', 'CompareController@compare')->name('compare');

});

//--------------- Dashboard ------------------//
Route::group(['prefix' => 'ru','name' => '','middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']],function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'can:admin-panel']], function () {
        Route::group(['prefix' => 'blog', 'as' => 'blog.', 'namespace' => 'Blog'], function () {
            Route::resource('videos', 'VideoController');
            Route::group(['prefix' => 'videos/{video}', 'as' => 'videos.'], function () {
                Route::post('remove-poster', 'VideoController@removePoster')->name('remove-poster');
                Route::post('remove-video', 'VideoController@removeVideo')->name('remove-video');
                Route::post('publish', 'VideoController@publish')->name('publish');
                Route::post('discard', 'VideoController@discard')->name('discard');
            });

            Route::resource('posts', 'PostController');
            Route::group(['prefix' => 'posts/{post}', 'as' => 'posts.'], function () {
                Route::post('remove-file', 'PostController@removeFile')->name('remove-file');
                Route::post('publish', 'PostController@publish')->name('publish');
                Route::post('discard', 'PostController@discard')->name('discard');
            });
        });

        Route::resource('banners', 'BannerController');
        Route::group(['prefix' => 'banners/{banner}', 'as' => 'banners.'], function () {
            Route::post('remove-file', 'BannerController@removeFile')->name('remove-file');
            Route::post('publish', 'BannerController@publish')->name('publish');
            Route::post('discard', 'BannerController@discard')->name('discard');
        });

        Route::resource('sliders', 'SlidersController');
        Route::group(['prefix' => 'sliders/{slider}', 'as' => 'sliders.'], function () {
            Route::post('first', 'SlidersController@first')->name('first');
            Route::post('up', 'SlidersController@up')->name('up');
            Route::post('down', 'SlidersController@down')->name('down');
            Route::post('last', 'SlidersController@last')->name('last');
        });

        Route::resource('discounts', 'DiscountController');
        Route::group(['prefix' => 'discounts/{discount}', 'as' => 'discounts.'], function () {

app/Http/Controllers/Admin/Blog/PostController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Entity\Blog\Post;
use App\Entity\Category;
use App\Helpers\ImageHelper;
use App\Helpers\ProductHelper;
use App\Http\Requests\Admin\Blog\Posts\CreateRequest;
use App\Http\Requests\Admin\Blog\Posts\UpdateRequest;
use App\Services\Manage\Blog\PostService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    private $service;

    public function __construct(PostService $service)
    {
        $this->middleware('can:manage-blog-posts');
        $this->service = $service;
    }

    public function index()
    {
        $posts = Post::with(['category'])->paginate(10);

        return view('admin.blog.posts.index', compact('posts'));
    }

    public function create()
    {
        $categories = ProductHelper::getCategoryList();

        return view('admin.blog.posts.create', compact('categories'));
    }


    public function store(CreateRequest $request)
    {
        $post = $this->service->create($request);
        session()->flash('message', 'запись обновлён ');

        return redirect()->route('admin.blog.posts.show', $post);
    }


    public function show(Post $post)
    {
        return view('admin.blog.posts.show', compact('post'));
    }

    public function edit(Post $post)
    {

        $categories = ProductHelper::getCategoryList();

        return view('admin.blog.posts.edit', compact('post', 'categories'));
    }

    public function update(UpdateRequest $request, Post $post)
    {
        $post = $this->service->update($post->id, $request);
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.blog.posts.show', $post);
    }

    public function destroy(Post $post)
    {
        if ($post->created_by !== Auth::user()->id && !Auth::user()->isAdmin()) {
            return redirect()->route('admin.blog.posts.index');
        }

        Storage::disk('public')->deleteDirectory('/files/' . ImageHelper::FOLDER_POSTS . '/' . $post->id);

        $post->delete();
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.blog.posts.index');
    }

    public function publish(Post $post)
    {
        try {
            $this->service->publish($post->id);
            session()->flash('message', 'запись обновлён ');
            return redirect()->route('admin.blog.posts.show', $post);
        } catch (\Exception $e) {
            session()->flash('error', 'Произошла ошибка');
            return back()->with('error', $e->getMessage());
        }
    }

    public function discard(Post $post)
    {
        try {
            $this->service->discard($post->id);

            return redirect()->route('admin.blog.posts.show', $post);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }
    }

    public function removeFile(Post $post)
    {
        if ($this->service->removeFile($post->id)) {
            return response()->json('The file is successfully deleted!');
        }
        return response()->json('The file is not deleted!', 400);
    }

}

app/Http/Controllers/Admin/Blog/VideoController.php
<?php

namespace App\Http\Controllers\Admin\Blog;


use App\Entity\Category;
use App\Entity\Blog\Video;
use App\Helpers\ImageHelper;
use App\Helpers\ProductHelper;
use App\Http\Requests\Admin\Blog\Videos\CreateRequest;
use App\Http\Requests\Admin\Blog\Videos\UpdateRequest;
use App\Services\Manage\Blog\VideoService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class VideoController extends Controller
{
    private $service;

    public function __construct(VideoService $service)
    {
        $this->middleware('can:manage-blog-videos');
        $this->service = $service;
    }

    public function index()
    {
        $videos = Video::paginate(10);

        return view('admin.blog.videos.index', compact('videos'));
    }

    public function create()
    {
        $categories = ProductHelper::getCategoryList();

        return view('admin.blog.videos.create', compact('categories'));
    }


    public function store(CreateRequest $request)
    {
        $video = $this->service->create($request);
        session()->flash('message', 'запись обновлён ');

        return redirect()->route('admin.blog.videos.show', $video);
    }


    public function show(Video $video)
    {
        return view('admin.blog.videos.show', compact('video'));
    }

    public function edit(Video $video)
    {
        $categories = ProductHelper::getCategoryList();
        return view('admin.blog.videos.edit', compact('video', 'categories'));
    }

    public function update(UpdateRequest $request, Video $video)
    {
        $video = $this->service->update($video->id, $request);
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.blog.videos.show', $video);
    }

    public function destroy(Video $video)
    {
        if($video->created_by != Auth::user()->id && !Auth::user()->isAdmin()) {
            return redirect()->route('admin.blog.videos.index');
        }

        Storage::disk('public')->deleteDirectory('/files/' . ImageHelper::FOLDER_VIDEOS . '/' . $video->id);

        $video->delete();
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.blog.videos.index');
    }

    public function publish(Video $video)
    {
        try {
            $this->service->publish($video->id);

            return redirect()->route('admin.blog.videos.show', $video);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }
    }

    public function discard(Video $video)
    {
        try {
            $this->service->discard($video->id);
            session()->flash('message', 'запись обновлён ');
            return redirect()->route('admin.blog.videos.show', $video);
        } catch (\Exception $e) {
            session()->flash('error', 'Произошла ошибка');
            return back()->with('error', $e->getMessage());
        }
    }

    public function removePoster(Video $video)
    {
        if ($this->service->removePoster($video->id)) {
            return response()->json('The poster is successfully deleted!');
        }
        return response()->json('The poster is not deleted!', 400);
    }

    public function removeVideo(Video $video)
    {
        if ($this->service->removeVideo($video->id)) {
            return response()->json('The video file is successfully deleted!');
        }
        return response()->json('The video file is not deleted!', 400);
    }

}

app/Http/Controllers/Api/VideosController.php
<?php

namespace App\Http\Controllers\Api;


use App\Entity\Blog\Video;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VideosController extends Controller
{


    public function index(Request $request)
    {
        if($request->has('category_id')){
            $data = Video::whereIn('category_id',$request->category_id)->paginate(12);
            return response()->json($data);
        }

        $data = Video::paginate(12);
        return response()->json($data);
    }
}

resources/views/admin/blog/videos/create.blade.php
@extends('layouts.admin.page')

@section('content')
    <form method="POST" action="{{ route('admin.blog.videos.store') }}" enctype="multipart/form-data">
        @csrf

        @include('partials.admin._nav')

        @include('admin.blog.videos._form', ['video' => null])
    </form>
@endsection

{{--@section('content')--}}
{{--    <div class="row">--}}

{{--        <div class="col-md-12">--}}
{{--            <div class="panel panel-default">--}}
{{--                <div class="panel-heading">--}}
{{--                    <h2>--}}
{{--                        Create Videos--}}

{{--                        <a href="{{ url('admin/videos') }}" class="btn btn-default pull-right">Go Back</a>--}}
{{--                    </h2>--}}
{{--                </div>--}}

{{--                <div class="panel-body">--}}
{{--                    {!! Form::open(['url' => '/admin/videos', "enctype" => "multipart/form-data", 'class' => 'form-horizontal', 'role' => 'form']) !!}--}}

{{--                        @include('admin.blog.videos._form')--}}

{{--                        <div class="form-group">--}}
{{--                            <div class="col-md-8 col-md-offset-2">--}}
{{--                                <button type="submit" class="btn btn-primary">--}}
{{--                                    Create--}}
{{--                                </button>--}}
{{--                            </div>--}}
{{--                        </div>--}}

{{--                    {!! Form::close() !!}--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}

{{--    </div>--}}
{{--@endsection--}}

resources/views/admin/blog/videos/edit.blade.php
@extends('layouts.admin.page')

@section('content')
    <form method="POST" action="{{ route('admin.blog.videos.update', $video) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        @include('partials.admin._nav')

        @include('admin.blog.videos._form')
    </form>
@endsection

{{--@section('content')--}}
{{--    <div class="row">--}}

{{--        <div class="col-md-12">--}}
{{--            <div class="panel panel-default">--}}
{{--                <div class="panel-heading">--}}
{{--                    <h2>--}}
{{--                        Edit Videos--}}

{{--                        <a href="{{ url('admin/videos') }}" class="btn btn-default pull-right">Go Back</a>--}}
{{--                    </h2>--}}
{{--                </div>--}}

{{--                <div class="panel-body">--}}
{{--                    {!! Form::model($post, ['method' => 'PUT', "enctype" => "multipart/form-data", 'url' => "/admin/videos/{$post->id}", 'class' => 'form-horizontal', 'role' => 'form']) !!}--}}

{{--                        @include('admin.blog.videos._form')--}}

{{--                        <div class="form-group">--}}
{{--                            <div class="col-md-8 col-md-offset-2">--}}
{{--                                <button type="submit" class="btn btn-primary">--}}
{{--                                    Update--}}
{{--                                </button>--}}
{{--                            </div>--}}
{{--                        </div>--}}

{{--                    {!! Form::close() !!}--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}

{{--    </div>--}}
{{--@endsection--}}

resources/views/admin/blog/videos/index.blade.php
@extends('layouts.admin.page')

@php($isAdmin = Auth::user()->isAdmin())

@section('content')
    <div class="row">
        <p><a href="{{ route('admin.blog.videos.create') }}" class="btn btn-success">@lang('adminlte.create')</a></p>

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>@lang('adminlte.image')</th>
                                <th>@lang('adminlte.title')</th>
                                <th>@lang('adminlte.description')</th>
                                <th>@lang('adminlte.author')</th>
                                <th>@lang('adminlte.category.name')</th>
                                <th>@lang('adminlte.status')</th>
                            </tr>
                        </thead>
                        <tbody>

                        @foreach($videos as $video)
                            <tr>
                                <td>
                                    @if ($video->poster)
                                        <a href="{{ $video->posterOriginal }}" target="_blank"><img src="{{ $video->posterThumbnail }}" alt=""></a>
                                    @endif
                                </td>
                                <td><a href="{{ route('admin.blog.videos.show', $video) }}">{{ $video->title }}</a></td>
                                <td>{!! $video->description !!}</td>
                                <td>
                                    @if ($isAdmin)
                                        <a href="{{ route('admin.users.show', $video->createdBy) }}">{{ $video->createdBy->name }}</a>
                                    @else
                                        {{ $video->createdBy->name }}
                                    @endif
                                </td>
                                <td><a href="{{ route('admin.categories.show', $video->category) }}">{{ $video->category->name }}</a></td>
                                <td>{!! $video->statusLabel() !!}</td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>

                    {!! $videos->links() !!}
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/blog/videos/show.blade.php
@extends('layouts.admin.page')

@section('content')
    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.blog.videos.edit', $video) }}" class="btn btn-primary mr-1">{{ trans('adminlte.edit') }}</a>

        @if (Auth::user()->isAdmin())
            <form method="POST" action="{{ route($video->isPublished() ? 'admin.blog.videos.discard' : 'admin.blog.videos.publish', $video) }}" class="mr-1">
                @csrf
                <button class="btn{{ $video->isPublished() ? ' btn-warning' : ' btn-success' }}"
                        onclick="return confirm('{{ trans('adminlte.delete_confirmation_message') }}')">
                    {{ trans($video->isPublished() ? 'adminlte.draft' : 'adminlte.publish') }}
                </button>
            </form>
        @endif

        <form method="POST" action="{{ route('admin.blog.videos.destroy', $video) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger" onclick="return confirm('{{ trans('adminlte.delete_confirmation_message') }}')">{{ trans('adminlte.delete') }}</button>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-gray card-outline">
                <div class="card-header"><h3 class="card-title">{{ trans('adminlte.main') }}</h3></div>
                <div class="card-body">
                    <table class="table {{--table-bordered--}} table-striped projects">
                        <tbody>
                        <tr><th>ID</th><td>{{ $video->id }}</td></tr>
                        <tr><th>@lang('adminlte.name') Uz</th><td>{{ $video->title_uz }}</td></tr>
                        <tr><th>@lang('adminlte.name') Ru</th><td>{{ $video->title_ru }}</td></tr>
                        <tr><th>@lang('adminlte.name') En</th><td>{{ $video->title_en }}</td></tr>
                        <tr><th>@lang('adminlte.description') Uz</th><td>{!! $video->description_uz !!}</td></tr>
                        <tr><th>@lang('adminlte.description') Ru</th><td>{!! $video->description_ru !!}</td></tr>
                        <tr><th>@lang('adminlte.description') En</th><td>{!! $video->description_en !!}</td></tr>
                        <tr><th>@lang('adminlte.body') Uz</th><td>{!! $video->body_uz !!}</td></tr>
                        <tr><th>@lang('adminlte.body') Ru</th><td>{!! $video->body_ru !!}</td></tr>
                        <tr><th>@lang('adminlte.body') En</th><td>{!! $video->body_en !!}</td></tr>
                        <tr>
                            <th>@lang('adminlte.category.name')</th>
                            <td><a href="{{ route('admin.categories.show', $video->category) }}">{{ $video->category->name }}</a></td>
                        </tr>
                        <tr><th>@lang('adminlte.status')</th><td>{!! $video->statusLabel() !!}</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-gray card-outline">
                <div class="card-header"><h3 class="card-title">{{ trans('adminlte.logo') }}</h3></div>
                <div class="card-body">
                    <table class="table {{--table-bordered--}} table-striped projects">
                        <tbody>
                        <tr>
                            <th>@lang('adminlte.image')</th>
                            <td>
                                @if ($video->poster)
                                    <a href="{{ $video->posterOriginal }}" target="_blank"><img src="{{ $video->posterThumbnail }}"></a>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <th>@lang('adminlte.video')</th>
                            <td>
                                @if ($video->video)
                                    <a href="{{ $video->videoFile }}" target="_blank">{{ $video->videoFile }}</a>
                                @endif
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @if (Auth::user()->isAdmin())
        <div class="row">
            <div class="col-md-12">
                <div class="card card-gray card-outline">
                    <div class="card-header"><h3 class="card-title">@lang('adminlte.others')</h3></div>
                    <div class="card-body">
                        <table class="table {{--table-bordered--}} table-striped projects">
                            <tbody>
                            <tr>
                                <th>@lang('adminlte.created_by')</th>
                                <td><a href="{{ route('admin.users.show', $video->createdBy) }}">{{ $video->createdBy->name }}</a></td>
                            </tr>
                            <tr>
                                <th>@lang('adminlte.updated_by')</th>
                                <td><a href="{{ route('admin.users.show', $video->updatedBy) }}">{{ $video->updatedBy->name }}</a></td>
                            </tr>
                            <tr><th>@lang('adminlte.created_at')</th><td>{{ $video->created_at }}</td></tr>
                            <tr><th>@lang('adminlte.updated_at')</th><td>{{ $video->updated_at }}</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection