routes/web.php
    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
    Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

    Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
    Route::get('password/reset/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::get('password/reset/email', 'Auth\ForgotPasswordController@resetEmail')->name('password.reset.email');
    Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset/request', 'Auth\ForgotPasswordController@resetRequest')->name('password.reset.request');

    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    Route::get('verify/email', 'Auth\RegisterController@email')->name('email.verification');
    Route::get('verify/email/{token}', 'Auth\RegisterController@verifyEmail')->name('verify.email');
    Route::get('verify/email/resend', 'Auth\RegisterController@resendEmailShow')->name('resend.email.show');
    Route::post('verify/email/resend', 'Auth\RegisterController@resendEmail')->name('resend.email.verification');
    Route::get('verify/phone', 'Auth\RegisterController@phone')->name('phone.verification');
    Route::post('verify/phone', 'Auth\RegisterController@verifyPhone')->name('verify.phone');
    Route::get('verify/phone/resend', 'Auth\RegisterController@resendPhoneShow')->name('resend.phone.show');
    Route::post('verify/phone/resend', 'Auth\RegisterController@resendPhone')->name('resend.phone.verification');

    Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'User'], function () {
        Route::get('add-email', 'ProfileController@addEmailShow')->name('add-email-show');
        Route::get('add-phone', 'ProfileController@addPhoneShow')->name('add-phone-show');
        Route::post('add-email', 'ProfileController@addEmail')->name('add-email');
        Route::post('add-phone', 'ProfileController@addPhone')->name('add-phone');
        Route::get('verify/email', 'ProfileController@email')->name('email.verification');
        Route::get('verify/phone', 'ProfileController@phone')->name('phone.verification');
        Route::get('verify/email/{token}', 'ProfileController@verifyEmail')->name('verify.email');
        Route::post('verify/phone', 'ProfileController@verifyPhone')->name('verify.phone');
        Route::post('add-inform', 'ProfileController@update')->name('add-inform');

        Route::post('request-manager-role', 'ProfileController@requestManagerRole')->name('manager.request');

        Route::get('add-photo', 'ProfileController@addPhoto')->name('add-photo');

        Route::get('change-password', 'ProfileController@changePasswordPage')->name('change-password');
        Route::post('change-password', 'ProfileController@changePassword')->name('change-password');
    });

    Route::get('home', 'HomeController@index')->name('home');
    Route::get('', 'HomeController@index')->name('front-home');

    Route::get('search', 'SearchResultsController@searchResults')->name('search');
    Route::get('search-product-filter', 'SearchResultsController@SearchFilter')->name('search-product-filter');


    Route::get('auth', 'AuthController@auth')->name('auth');
    Route::get('mail', 'MailController@mail')->name('mail');
    Route::get('sms', 'SmsController@sms')->name('sms');

    Route::get('blogs', 'BlogController@blogs')->name('blogs');
    Route::get('blogs/{blog}', 'BlogController@show')->name('blogs.show');
    Route::get('brands', 'BrandsController@brands')->name('brands');
    Route::get('brands/{brand}', 'BrandsController@show')->name('brands.show');

    Route::get('cart', 'CartController@cart')->name('cart');
    Route::get('checkout', 'CheckoutController@checkout')->name('checkout');
    Route::post('pay', 'PayController@pay')->name('pay');
    Route::post('finalStep', 'PayController@finalStep')->name('finalStep');
    Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], function () {
        Route::get('', 'CatalogController@catalog')->name('list');
    });
    Route::get('catalogsection', 'CategoryController@index')->name('catalogsection');

    Route::get('/delivery', 'DeliveryGuarantyPaymentController@deliveryGuarantyPayment')->name('delivery'); // delivery, guaranty, payment are combined
    Route::get('popular', 'PopularController@popular')->name('popular');

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('show/{product}', 'ProductController@show')->name('show');
        Route::post('{product}/add-review', 'ProductController@addReview')->name('add-review');
        Route::group(['prefix' => '{product}/cart', 'as' => 'cart.'], function () {
            Route::get('add', 'ProductController@addToCart')->name('add');
            Route::patch('update-cart', 'ProductController@update')->name('update');
            Route::delete('remove-from-cart', 'ProductController@remove')->name('remove');
        });
        Route::get('{product}/compare-with/{comparingProduct}', 'ProductController@compare')->name('compare');
        Route::get('new-products', 'ProductController@newProducts')->name('new-products');
    });

    Route::get('add-to-cart/{id}', 'ProductController@addToCart')->name('addCard');
    Route::patch('update-cart', 'ProductController@update');
    Route::delete('remove-from-cart', 'ProductController@remove');

    Route::group(['prefix' => 'discounts', 'as' => 'discounts.'], function () {
        Route::get('', 'DiscountController@index')->name('index');
        Route::get('/{discount}', 'DiscountController@show')->name('show');
    });

    Route::group(['prefix' => 'shops', 'as' => 'shops.'], function () {
        Route::get('', 'ShopsController@index')->name('index');
        Route::get('{store}', 'ShopsController@view')->name('show');
    });


    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::get('/{products_path?}', 'CategoryController@show')->name('show')->where('products_path', '.+');
//        Route::get('{category}', 'CategoryController@show')->name('show');
    });

    Route::resource('/videos', 'VideosController');

    Route::group(['as' => 'user.','namespace' => 'User'], function () {
            Route::get('setting','ProfileController@index')->name('setting');
            Route::get('profile','ProfileController@show')->name('profile');
            Route::put('setting','ProfileController@update')->name('update');
            Route::get('favorites','FavoriteController@favorites')->name('favorites')->middleware('auth');
            Route::get('add-to-favorite/{product}','FavoriteController@addToFavorite')->name('favorites.add');
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/{page_path}', 'PageController@show')->name('show')->where('page_path', '.+');
    });

    Route::group(['prefix' => 'stores', 'as' => 'stores.'], function () {
        Route::get('', 'StoresController@index')->name('index');
        Route::get('{store}', 'StoresController@store')->name('show');
        Route::get('view/{store}', 'StoresController@view')->name('view');
        Route::get('stores', 'StoresController@view')->name('store');
    });

    Route::get('cart-list', 'CartController@index')->name('cart');
    Route::get('cart-header', 'CartController@showHeader');

    Route::get('compare', 'CompareController@compare')->name('compare');

});

//--------------- Dashboard ------------------//
Route::group(['prefix' => 'ru','name' => '','middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']],function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'can:admin-panel']], function () {
        Route::group(['prefix' => 'blog', 'as' => 'blog.', 'namespace' => 'Blog'], function () {
            Route::resource('videos', 'VideoController');
            Route::group(['prefix' => 'videos/{video}', 'as' => 'videos.'], function () {
                Route::post('remove-poster', 'VideoController@removePoster')->name('remove-poster');
                Route::post('remove-video', 'VideoController@removeVideo')->name('remove-video');
                Route::post('publish', 'VideoController@publish')->name('publish');
                Route::post('discard', 'VideoController@discard')->name('discard');
            });

            Route::resource('posts', 'PostController');
            Route::group(['prefix' => 'posts/{post}', 'as' => 'posts.'], function () {
                Route::post('remove-file', 'PostController@removeFile')->name('remove-file');
                Route::post('publish', 'PostController@publish')->name('publish');
                Route::post('discard', 'PostController@discard')->name('discard');
            });
        });

        Route::resource('banners', 'BannerController');
        Route::group(['prefix' => 'banners/{banner}', 'as' => 'banners.'], function () {
            Route::post('remove-file', 'BannerController@removeFile')->name('remove-file');
            Route::post('publish', 'BannerController@publish')->name('publish');
            Route::post('discard', 'BannerController@discard')->name('discard');
        });

        Route::resource('sliders', 'SlidersController');
        Route::group(['prefix' => 'sliders/{slider}', 'as' => 'sliders.'], function () {
            Route::post('first', 'SlidersController@first')->name('first');
            Route::post('up', 'SlidersController@up')->name('up');
            Route::post('down', 'SlidersController@down')->name('down');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;


use App\Entity\Category;
use App\Entity\Shop\Product;
use App\Entity\Shop\Value;
use App\Http\Requests\Products\ReviewRequest;
use App\Services\Manage\Shop\ProductService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{

    private $times = [
        7 * 24 * 3600,
        15 * 24 * 3600,
        30 * 24 * 3600,
    ];

    public function __construct()
    {
//        $this->middleware('auth');
    }

    public function show(Product $product)
    {
        $sessionProduct = ProductService::addProductToSession($product->id);
        $user = $product->createdBy;
        $otherProducts = Product::with(['mainPhoto', 'store'])->where('created_by', $user->id)->active()
            ->orderByDesc('created_at')->limit(10)->get();

        $similarProducts = Product::with(['mainPhoto', 'store'])->where('main_category_id', $product->main_category_id)->active()->limit(10)->get();
        $watchedProduct = Product::whereIn('id', $sessionProduct)->paginate(10);

        $shopProducts = Product::where(['store_id' => $product->store_id])->limit(8)->get();
        $index = 0;
        $length = count($this->times);
        $interestingProducts = null;
        while ($index < $length) {
            $query = Product::where('created_at', '>=', date('Y-m-d H:i:s', time() - $this->times[$index]));
            if ($query->exists()) {
                $interestingProducts = $query->active()->orderByDesc('rating')->orderByDesc('created_at')->limit(10)->get();
                break;
            }
            $index++;
        }

        return view('products.show', compact('product', 'otherProducts', 'similarProducts', 'interestingProducts', 'watchedProduct', 'shopProducts'));
    }

    public function addToCart($id)
    {
        $product = Product::find($id);

        if (!$product) {
            abort(404);
        }

        $cart = session()->get('cart');
//        dd($product->mainPhoto->file);

        if (!$cart) {
            $cart = [
                $id => [
                    "name" => $product->name,
                    "quantity" => 1,
                    "price" => $product->price_uzs,
                    "photo" => $product->mainPhoto->file
                ]
            ];

            session()->put('cart', $cart);

            return redirect()->back()->with('success', 'Product added to cart successfully!');
        }

        if (isset($cart[$id])) {
            $cart[$id]['quantity']++;

            session()->put('cart', $cart);

            return redirect()->back()->with('success', 'Product added to cart successfully!');

        }
        $cart[$id] = [
            "name" => $product->name,
            "quantity" => 1,
            "price" => $product->price_uzs,
            "photo" => $product->mainPhoto->file
        ];

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }

    public function update(Request $request)
    {
        if ($request->id and $request->quantity) {
            $cart = session()->get('cart');

            $cart[$request->id]["quantity"] = $request->quantity;

            session()->put('cart', $cart);
            session()->flash('success', 'Cart updated successfully');
        }
    }

    public function remove(Request $request)
    {
        if ($request->id) {
            $cart = session()->get('cart');

            if (isset($cart[$request->id])) {
                unset($cart[$request->id]);

                session()->put('cart', $cart);
            }

            session()->flash('success', 'Product removed successfully');
        }
    }

    public function addReview(ReviewRequest $request, Product $product)
    {
        $numberOfReviews = $product->number_of_reviews;
        $ratingSum = ($product->rating ?? 0) * $numberOfReviews;
        $ratingSum += $request->rating;
        $numberOfReviews++;
        $totalRating = $ratingSum / $numberOfReviews;

        DB::beginTransaction();
        try {
            $product->reviews()->create([
                'rating' => $request->rating,
                'advantages' => $request->advantages,
                'disadvantages' => $request->disadvantages,
                'comment' => $request->comment,
            ]);
            $product->update([
                'rating' => $totalRating,
                'number_of_reviews' => $numberOfReviews,
            ]);

            DB::commit();
            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollBack();
//            dd($e->getMessage());
            return back()->with('error', trans('validation.add_rating_twice_in_product_comment'));
        }
    }

    public function compare(Product $product, Product $comparingProduct)
    {
        if ($product->id === $comparingProduct->id || $product->main_category_id !== $comparingProduct->main_category_id) {
            abort(404);
            throw new \Exception('Products are not the same type!!!');
        }

        $values = Value::select(['shop_values.*', 'c.*', 'cg.*'])
            ->leftJoin('shop_characteristics as c', 'shop_values.characteristic_id', '=', 'c.id')
            ->leftJoin('shop_characteristic_groups as cg', 'c.group_id', '=', 'cg.id')
            ->where('shop_values.product_id', $product->id)
            ->orderBy('cg.order')->orderBy('shop_values.sort')->get();

        if ($values->isNotEmpty()) {
            $tempValues = [];
            $comparingTempValues = [];
            $groupId = $values[0]->characteristic->group_id;
            $i = 0;
            foreach ($values as $value) {
                if ($groupId === $value->group_id) {
                    $tempValues[$i][] = $value;
                } else {
                    $groupId = $value->characteristic->group_id;
                    $tempValues[++$i][] = $value;
                }
                $comparingTempValues[$i][] = $comparingProduct->values()->where('characteristic_id', $value->characteristic_id)->first() ?? null;
            }
            $groupValues = $tempValues;
            $comparingGroupValues = $comparingTempValues;
            unset($tempValues, $comparingTempValues);
        } else {
            $groupValues = null;
            $comparingGroupValues = null;
        }

        return view('compare.compare', compact('product', 'comparingProduct', 'groupValues', 'comparingGroupValues'));
    }

    public function newProducts(Request $request,Category $category)
    {
        $newProducts = Product::where('new', true);
        if ($request->categoryName and $request->categoryName !== 'all'){
            $newProducts = $newProducts->where('main_category_id', $request->categoryName);
        }

        $ratings = [];
        $min_price = 0;
        $max_price = 1;

        $newProducts = $newProducts->paginate(12);
        $newProductIds = $newProducts->pluck('main_category_id')->toArray();

        foreach ($newProducts as $i => $product) {
            if ($min_price === 0) {
                $min_price = $product->price_uzs;
            } elseif ($min_price > $product->price_uzs) {
                $min_price = $product->price_uzs;
            } elseif ($max_price < $product->price_uzs) {
                $max_price = $product->price_uzs;
            }
            $ratings[$i] = [
                'id' => $product->id,
                'rating' => $product->rating,
            ];
        }
        $categories = Category::whereIn('id', $newProductIds)->get();

        $parentCategory =  $category->parent()->get()->toTree();
        $rootCategoryShow = true;

        return view('products.new-products', compact('newProducts', 'ratings', 'min_price', 'max_price', 'parentCategory', 'categories', 'rootCategoryShow'));
    }
}

resources/views/products/full-des-of-singlep.blade.php
<section>
    <div class="outter-full-des-of-singlep">
        {!! $product->description !!}
    </div>
</section>

resources/views/products/single-product-with-des.blade.php
<section>
    <div class="outter-single-product-with-des">
        <?php
        if ($product->classFavorite($product->id)) {
            $favoriteClass = "selected_like";
        } else {
            $favoriteClass = '';
        }

        if ($product->classCart($product->id)) {
            $cartClass = "selected_cart";
        } else {
            $cartClass = '';
        }
        ?>
        <h4 class="title">{{ $product->name }}</h4>
        <div class="inner-single-product-with-des">
            <div class="images">
                @if ($product->mainPhoto)
                    <div class="big-image">
                        <img src="{{ $product->mainPhoto->fileThumbnail }}"  id="productMainPhoto">
                    </div>
                @endif


                <div class="several-images owl-theme owl-carousel">
                    @php($currentSlide = 0)
                    @if ($product->mainPhoto)
                        <img class="demo cursor" src="{{ $product->mainPhoto->fileThumbnail }}"
                             onclick='currentSlide({{ $currentSlide }}, "{{ $product->mainPhoto->fileThumbnail }}")'>
                        @php($currentSlide++)
                    @endif
                    @foreach($product->photos as $photo)
                        <img class="demo cursor" src="{{ $photo->fileOriginal }}"
                             onclick='currentSlide({{ $currentSlide }}, "{{ $photo->fileOriginal }}")'>
                        @php($currentSlide++)
                    @endforeach
                </div>
            </div>
            <div class="description">
                <div class="text-description">
                    <div class="rating-des">
                        <div class="rate">
                            <div id="rateYo_one0"></div>
                        </div>
                        <div class="comment">
                            <i class="mbcomment"></i>
                            <span>{{ $product->number_of_reviews }} @lang('frontend.reviews')</span>
                        </div>
                    </div>
                    <p class="title">@lang('frontend.product.characteristics')</p>
                    @foreach($product->allCharacteristics as $characteristics)
                        @if($characteristics->characteristic->main)
                            <p>{!! $characteristics->characteristic->name !!}:
                                <span>
                                    @foreach($product->modificationsForProduct($characteristics->characteristic_id) as $modifications) {{ $modifications->value }} @endforeach
                                </span>
                            </p>
                        @endif
                    @endforeach
{{--                    <a href="#pills-characteristics">@lang('frontend.product.all_characteristics')</a>--}}
                </div>
                <div class="color-delivery-des">
                    <form action="#">
                        @foreach($product->allCharacteristics as $modification)

                           @if($modification->characteristic->main == false && $modification->characteristic->type != \App\Entity\Shop\Characteristic::TYPE_COLOR)
                                   @if(!empty($modification->modifications->value))
                                        <p>{{ $modification->characteristic->name }}:</p>
                                   @endif
                                    @foreach($product->modificationsForProduct($modification->characteristic_id) as $modifications)
                                            <span class="pr-des-radio-buttons">
                                                <div class="value-modification" id="value-modification"
                                                     data-actual-price="{{ trans('frontend.product.price', ['price' => $modifications->price_uzs]) }}"
                                                     data-actual-modification-id="{{ $modifications->id }}"
                                                     data-actual-product-id="{{ $product->id }}"
                                                     data-final-price="{{ trans('frontend.product.price', ['price' => $modifications->currentPriceUzs]) }}">
                                                    {{ $modifications->value }}
                                                </div>
                                            </span>
                                    @endforeach
                           @endif
                        @if($modification->characteristic->main == false && $modification->characteristic->type == \App\Entity\Shop\Characteristic::TYPE_COLOR)
                            <p>@lang('frontend.color'): <span
                                    id="color-modification-name">{{ $modification->characteristic->name }}</span></p>
                            <div class="colors pr-des-radio-buttons3">

                                @foreach($product->colorModifications($modification->characteristic_id) as $modification)
                                    <div class="color color-modification" id="color-modification">
                                        <div style="background-color: {{ $modification->value }}"
                                             data-name="{{ $modification->name }}"
                                             data-actual-modification-id="{{ $modification->id }}"
                                             data-actual-product-id ="{{ $product->id }}"
                                             data-actual-price="{{ trans('frontend.product.price', ['price' => $modification->price_uzs]) }}"
                                             data-final-price="{{ trans('frontend.product.price', ['price' => $modification->currentPriceUzs]) }}"
                                        ></div>
                                    </div>
                                @endforeach
                            </div>
                        @endif
                        @endforeach
                    </form>
                    <div class="current-old-price horizontal">
                        <h5 class="price"
                            id="final-product-price">@lang('frontend.product.price', ['price' => $product->currentPriceUzs])</h5>
                        <h6 class="old-price"
                            id="actual-product-price">@lang('frontend.product.price', ['price' => $product->price_uzs])</h6>
                    </div>
                    <div class="item-action-icons">
                        <div class="cart <?php echo $cartClass ?>" id="cart-button"
                             data-name="{{ $product->name }}"
                             data-url="{{ $product->mainPhoto ? $product->mainPhoto->fileOriginal : asset('images/tv6.png') }}"
                             data-price="{{ $product->currentPriceUzs }}"
                             data-id="c{{ $product->id }}"
                             onclick="addCart({{ $product->id }})">
                            <i class="mbcart"></i>@lang('frontend.product.to_cart')
                        </div>
                        <div class="libra" id="cartActive{{ $product->id }}"
                             onclick="addToComparing({{ $product->id }})"
                             data-id="l{{ $product->id }}">
                            <i class="mbtocompare"></i>
                        </div>
                        <div class="like <?php echo $favoriteClass ?>" onclick="addToFavorite({{ $product->id }})"><i
                                class="mbfavorite"></i></div>
                    </div>
                    <input type="hidden" id="productModification{{ $product->id }}">
                    <div class="delivery-options">
                        <div><i class="mbdelievery"></i>@lang('frontend.product.delivery_time', ['hour' => date('g', $product->discountExpiresAt)])</div>
                        <div><i class="mbbox"></i>@lang('frontend.product.pickup_time', ['date' => date("d.m.Y", strtotime($product->discount_ends_at))])</div>
                    </div>
                    <div class="sub-title bottom position-static">
                        <div class="shop-name-logo">
                            <a href="{{ route('stores.view',['store' => $product->store]) }}"><img
                                    src="{{ $product->store->logoThumbnail ?? null }}" alt="" class="img-rounded"></a>
                            <div>
                                <b class="title"><a
                                        href="{{ route('stores.view',['store' => $product->store]) }}">{!! $product->store->name !!}</a></b>
                            </div>
                        </div>
                    </div>
                </div>
                <script>
                    localStorage.getItem('compare_product').split(',').forEach(el => {
                        if (el === "{{$product->id}}") {
                            $(`[data-id="l${el}"]`).addClass('selected_libra');
                        }
                    })
                    @guest
                    JSON.parse(localStorage.getItem('product_id')).forEach(el => {
                        if (el.product_id === "{{$product->id}}") {
                            $(`[data-id="c${el.product_id}"]`).addClass('selected_cart');
                        }
                    })
                    @endguest
                </script>
            </div>
        </div>
    </div>
</section>
@include('pages.rating-js', ['products' => $product, 'type' => '"one"'])

<script>

    function addToComparing(id) {
        if (localStorage.getItem('compare_product')) {
            let compare_products = '';
            let exist = false;
            let product_id = localStorage.getItem('compare_product')
            let cart_product_check = product_id.split(',');
            for (let i = 0; i <= cart_product_check.length; i++) {
                if (cart_product_check[i] == id) {
                    console.log('exists')
                    exist = true;
                }
            }
            if (!exist) {
                if (cart_product_check.length < 1){
                    compare_products += product_id;
                    compare_products += id + ',';
                    localStorage.setItem('compare_product', compare_products + '');
                    let containerCounter = $('.counter');
                    containerCounter.text(cart_product_check.length);
                }
                if (cart_product_check.length <= 3 && cart_product_check.length >= 1) {
                    $.ajax({
                        url: '/check-compare/' + id+'/' + cart_product_check[0] ,
                        method: 'GET',
                        success: function (data) {
                            if (data === "success"){
                                compare_products += product_id;
                                compare_products += id + ',';
                                localStorage.setItem('compare_product', compare_products + '');
                                let containerCounter = $('.counter');
                                containerCounter.text(cart_product_check.length);
                            }else{
                                alert('{{ trans('frontend.compare_not_fit') }}')
                                $(`[data-id="l${id}"]`).removeClass('selected_libra')
                            }
                        }, error: function (data) {
                            // console.log(data);
                        }
                    });
                } else {
                    alert('{{ trans('frontend.compare_full') }}')
                    $(`[data-id="l${id}"]`).removeClass('selected_libra')
                }

            }
        } else {
            localStorage.setItem('compare_product', id + ',');
        }
    }
    function addToFavorite(id) {
        let product_id = {};
        product_id.id = id;
        $.ajax({
            url: '{{ route('user.add-to-favorite',$product) }}',
            method: 'GET',
            success: function (data) {
                console.log(data);
            }, error: function (data) {
                console.log(data);
            }
        })
    }



    //SLIDER
    var slideIndex = 0;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n, url) {
        showSlides(n);
        setImage(url)
    }

    function setImage(imageUrl) {
        $('#productMainPhoto').attr('src', `https://shop.sec.uz${imageUrl}`)
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("big-image");
        var dots = document.getElementsByClassName("demo");
        // debugger
        if (n > slides.length) {
            slideIndex = 1
        }
        if (n < 1) {
            slideIndex = slides.length
        }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }

        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";

        for(let j = 0; j < dots.length; j++) {
            if(j === n) {
                dots[j].classList.add('active')
            } else {
                dots[j].classList.remove('active')
            }
        }
    }
</script>