routes/web.php
    Route::get('verify/email', 'Auth\RegisterController@email')->name('email.verification');
    Route::get('verify/email/{token}', 'Auth\RegisterController@verifyEmail')->name('verify.email');
    Route::get('verify/email/resend', 'Auth\RegisterController@resendEmailShow')->name('resend.email.show');
    Route::post('verify/email/resend', 'Auth\RegisterController@resendEmail')->name('resend.email.verification');
    Route::get('verify/phone', 'Auth\RegisterController@phone')->name('phone.verification');
    Route::post('verify/phone', 'Auth\RegisterController@verifyPhone')->name('verify.phone');
    Route::get('verify/phone/resend', 'Auth\RegisterController@resendPhoneShow')->name('resend.phone.show');
    Route::post('verify/phone/resend', 'Auth\RegisterController@resendPhone')->name('resend.phone.verification');

    Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'User'], function () {
        Route::get('add-email', 'ProfileController@addEmailShow')->name('add-email-show');
        Route::get('add-phone', 'ProfileController@addPhoneShow')->name('add-phone-show');
        Route::post('add-email', 'ProfileController@addEmail')->name('add-email');
        Route::post('add-phone', 'ProfileController@addPhone')->name('add-phone');
        Route::get('verify/email', 'ProfileController@email')->name('email.verification');
        Route::get('verify/phone', 'ProfileController@phone')->name('phone.verification');
        Route::get('verify/email/{token}', 'ProfileController@verifyEmail')->name('verify.email');
        Route::post('verify/phone', 'ProfileController@verifyPhone')->name('verify.phone');
        Route::post('add-inform', 'ProfileController@update')->name('add-inform');

        Route::post('request-manager-role', 'ProfileController@requestManagerRole')->name('manager.request');

        Route::get('add-photo', 'ProfileController@addPhoto')->name('add-photo');

        Route::get('change-password', 'ProfileController@changePasswordPage')->name('change-password');
        Route::post('change-password', 'ProfileController@changePassword')->name('change-password');
    });

    Route::get('home', 'HomeController@index')->name('home');
    Route::get('', 'HomeController@index')->name('front-home');

    Route::get('search', 'SearchResultsController@searchResults')->name('search');
    Route::get('search-product-filter', 'SearchResultsController@SearchFilter')->name('search-product-filter');


    Route::get('auth', 'AuthController@auth')->name('auth');
    Route::get('mail', 'MailController@mail')->name('mail');
    Route::get('sms', 'SmsController@sms')->name('sms');

    Route::get('blogs', 'BlogController@blogs')->name('blogs');
    Route::get('blogs/{blog}', 'BlogController@show')->name('blogs.show');
    Route::get('brands', 'BrandsController@brands')->name('brands');
    Route::get('brands/{brand}', 'BrandsController@show')->name('brands.show');

    Route::get('cart', 'CartController@cart')->name('cart');
    Route::get('checkout', 'CheckoutController@checkout')->name('checkout');
    Route::post('pay', 'PayController@pay')->name('pay');
    Route::post('finalStep', 'PayController@finalStep')->name('finalStep');
    Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], function () {
        Route::get('', 'CatalogController@catalog')->name('list');
    });
    Route::get('catalogsection', 'CategoryController@index')->name('catalogsection');

    Route::get('/delivery', 'DeliveryGuarantyPaymentController@deliveryGuarantyPayment')->name('delivery'); // delivery, guaranty, payment are combined
    Route::get('popular', 'PopularController@popular')->name('popular');

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('show/{product}', 'ProductController@show')->name('show');
        Route::post('{product}/add-review', 'ProductController@addReview')->name('add-review');
        Route::group(['prefix' => '{product}/cart', 'as' => 'cart.'], function () {
            Route::get('add', 'ProductController@addToCart')->name('add');
            Route::patch('update-cart', 'ProductController@update')->name('update');
            Route::delete('remove-from-cart', 'ProductController@remove')->name('remove');
        });
        Route::get('{product}/compare-with/{comparingProduct}', 'ProductController@compare')->name('compare');
        Route::get('new-products', 'ProductController@newProducts')->name('new-products');
    });

    Route::get('add-to-cart/{id}', 'ProductController@addToCart')->name('addCard');
    Route::patch('update-cart', 'ProductController@update');
    Route::delete('remove-from-cart', 'ProductController@remove');

    Route::group(['prefix' => 'discounts', 'as' => 'discounts.'], function () {
        Route::get('', 'DiscountController@index')->name('index');
        Route::get('/{discount}', 'DiscountController@show')->name('show');
    });

    Route::group(['prefix' => 'shops', 'as' => 'shops.'], function () {
        Route::get('', 'ShopsController@index')->name('index');
        Route::get('{store}', 'ShopsController@view')->name('show');
    });


    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::get('/{products_path?}', 'CategoryController@show')->name('show')->where('products_path', '.+');
//        Route::get('{category}', 'CategoryController@show')->name('show');
    });

    Route::resource('/videos', 'VideosController');

    Route::group(['as' => 'user.','namespace' => 'User'], function () {
            Route::get('setting','ProfileController@index')->name('setting');
            Route::get('profile','ProfileController@show')->name('profile');
            Route::put('setting','ProfileController@update')->name('update');
            Route::get('favorites','FavoriteController@favorites')->name('favorites')->middleware('auth');
            Route::get('add-to-favorite/{product}','FavoriteController@addToFavorite')->name('favorites.add');
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/{page_path}', 'PageController@show')->name('show')->where('page_path', '.+');
    });

    Route::group(['prefix' => 'stores', 'as' => 'stores.'], function () {
        Route::get('', 'StoresController@index')->name('index');
        Route::get('{store}', 'StoresController@store')->name('show');
        Route::get('view/{store}', 'StoresController@view')->name('view');
        Route::get('stores', 'StoresController@view')->name('store');
    });

    Route::get('cart-list', 'CartController@index')->name('cart');
    Route::get('cart-header', 'CartController@showHeader');

    Route::get('compare', 'CompareController@compare')->name('compare');

});

//--------------- Dashboard ------------------//
Route::group(['prefix' => 'ru','name' => '','middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']],function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'can:admin-panel']], function () {
        Route::group(['prefix' => 'blog', 'as' => 'blog.', 'namespace' => 'Blog'], function () {
            Route::resource('videos', 'VideoController');
            Route::group(['prefix' => 'videos/{video}', 'as' => 'videos.'], function () {
                Route::post('remove-poster', 'VideoController@removePoster')->name('remove-poster');
                Route::post('remove-video', 'VideoController@removeVideo')->name('remove-video');
                Route::post('publish', 'VideoController@publish')->name('publish');
                Route::post('discard', 'VideoController@discard')->name('discard');
            });

            Route::resource('posts', 'PostController');
            Route::group(['prefix' => 'posts/{post}', 'as' => 'posts.'], function () {
                Route::post('remove-file', 'PostController@removeFile')->name('remove-file');
                Route::post('publish', 'PostController@publish')->name('publish');
                Route::post('discard', 'PostController@discard')->name('discard');
            });
        });

        Route::resource('banners', 'BannerController');
        Route::group(['prefix' => 'banners/{banner}', 'as' => 'banners.'], function () {
            Route::post('remove-file', 'BannerController@removeFile')->name('remove-file');
            Route::post('publish', 'BannerController@publish')->name('publish');
            Route::post('discard', 'BannerController@discard')->name('discard');
        });

        Route::resource('sliders', 'SlidersController');
        Route::group(['prefix' => 'sliders/{slider}', 'as' => 'sliders.'], function () {
            Route::post('first', 'SlidersController@first')->name('first');
            Route::post('up', 'SlidersController@up')->name('up');
            Route::post('down', 'SlidersController@down')->name('down');
            Route::post('last', 'SlidersController@last')->name('last');
        });

        Route::resource('discounts', 'DiscountController');
        Route::group(['prefix' => 'discounts/{discount}', 'as' => 'discounts.'], function () {
            Route::post('remove-file', 'DiscountController@removeFile')->name('remove-file');
            Route::post('common', 'DiscountController@common')->name('common');
            Route::post('rared', 'DiscountController@rared')->name('rared');
        });

        Route::get('', 'HomeController@index')->name('home');

        Route::get('users/manager-role-requests', 'UserController@requestsIndex')->name('users.requests');
        Route::resource('users', 'UserController');
        Route::group(['prefix' => 'users/{user}', 'as' => 'users.'], function () {
            Route::post('remove-avatar', 'UserController@removeAvatar')->name('remove-avatar');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Brand;
use App\Entity\Category;
use App\Helpers\LanguageHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Shop\Categories\CreateRequest;
use App\Http\Requests\Admin\Shop\Categories\UpdateRequest;
use App\Services\Manage\Shop\CategoryService;

class CategoryController extends Controller
{
    private $service;

    public function __construct(CategoryService $service)
    {
        $this->middleware('can:manage-categories');
        $this->service = $service;
    }

    public function index()
    {
        $categories = Category::defaultOrder()->withDepth()->get();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        $parents = Category::defaultOrder()->withDepth()->get();
        $brands = Brand::orderByDesc('updated_at')->pluck('name_' . LanguageHelper::getCurrentLanguagePrefix(), 'id');

        return view('admin.categories.create', compact('parents', 'brands'));
    }

    public function store(CreateRequest $request)
    {
        $category = $this->service->create($request);
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.categories.show', $category);
    }

    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));
    }

    public function edit(Category $category)
    {
        $parents = Category::defaultOrder()->withDepth()->get();
        $brands = Brand::orderByDesc('updated_at')->pluck('name_' . LanguageHelper::getCurrentLanguagePrefix(), 'id');

        return view('admin.categories.edit', compact('category', 'parents', 'brands'));
    }

    public function update(UpdateRequest $request, Category $category)
    {
        $category = $this->service->update($category->id, $request);
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.categories.show', $category);
    }

    public function first(Category $category)
    {
        if ($first = $category->siblings()->defaultOrder()->first()) {
            $category->insertBeforeNode($first);
        }

        return redirect()->route('admin.categories.index');
    }

    public function up(Category $category)
    {
        $category->up();

        return redirect()->route('admin.categories.index');
    }

    public function down(Category $category)
    {
        $category->down();

        return redirect()->route('admin.categories.index');
    }

    public function last(Category $category)
    {
        if ($last = $category->siblings()->defaultOrder('desc')->first()) {
            $category->insertAfterNode($last);
        }

        return redirect()->route('admin.categories.index');
    }

    public function destroy(Category $category)
    {
        $this->service->remove($category->id);
        session()->flash('message', 'запись обновлён ');
        return redirect()->route('admin.categories.index');
    }

    public function removePhoto(Category $category)
    {
        if ($this->service->removePhoto($category->id)) {
            return response()->json('The logo is successfully deleted!');
        }
        return response()->json('The logo is not deleted!', 400);
    }

    public function removeIcon(Category $category)
    {
        if ($this->service->removeIcon($category->id)) {
            return response()->json('The logo is successfully deleted!');
        }
        return response()->json('The logo is not deleted!', 400);
    }
}

resources/views/admin/categories/_form.blade.php
@if (!config('adminlte.enabled_laravel_mix'))
    @php($cssSectionName = 'css')
    @php($javaScriptSectionName = 'js')
@else
    @php($cssSectionName = 'mix_adminlte_css')
    @php($javaScriptSectionName = 'mix_adminlte_js')
@endif

@section($cssSectionName)
    <link rel="stylesheet" href="{{ mix('css/fileinput.css', 'build') }}">
@endsection
@include ('admin.layout.flash')
<div class="row">
    <div class="col-md-12">
        <div class="card card-gray card-outline">
            <div class="card-body">
                <div class="tab-content">
                    <div class="tab-pane active" id="uzbek" role="tabpanel">
                        <div class="form-group">
                            <label for="name_uz" class="col-form-label">Nomi</label>
                            <input id="name_uz" class="form-control{{ $errors->has('name_uz') ? ' is-invalid' : '' }}"
                                   name="name_uz" value="{{ old('name_uz', $category ? $category->name_uz : null)}}" required>
                            @if ($errors->has('name_uz'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('name_uz') }}</strong></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="description_uz" class="col-form-label">Tavsifi</label>
                            <textarea id="description_uz" class="form-control{{ $errors->has('description_uz') ? ' is-invalid' : '' }}"
                                      name="description_uz" rows="10">{{ old('description_uz', $category ? $category->description_uz : null)}}</textarea>
                            @if ($errors->has('description_uz'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('description_uz') }}</strong></span>
                            @endif
                        </div>
                    </div>
                    <div class="tab-pane" id="russian" role="tabpanel">
                        <div class="form-group">
                            <label for="name_ru" class="col-form-label">Название</label>
                            <input id="name_ru" class="form-control{{ $errors->has('name_ru') ? ' is-invalid' : '' }}" name="name_ru" value="{{ old('name_ru', $category ? $category->name_ru : null) }}" required>
                            @if ($errors->has('name_ru'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('name_ru') }}</strong></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="description_ru" class="col-form-label">Описание</label>
                            <textarea id="description_ru" class="form-control{{ $errors->has('description_ru') ? ' is-invalid' : '' }}"
                                      name="description_ru" rows="10">{{ old('description_ru', $category ? $category->description_ru : null)}}</textarea>
                            @if ($errors->has('description_ru'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('description_ru') }}</strong></span>
                            @endif
                        </div>
                    </div>
                    <div class="tab-pane" id="english" role="tabpanel">
                        <div class="form-group">
                            <label for="name_en" class="col-form-label">Name</label>
                            <input id="name_en" class="form-control{{ $errors->has('name_en') ? ' is-invalid' : '' }}" name="name_en" value="{{ old('name_en', $category ? $category->name_en : null) }}" required>
                            @if ($errors->has('name_en'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('name_en') }}</strong></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="description_en" class="col-form-label">Description</label>
                            <textarea id="description_en" class="form-control{{ $errors->has('description_en') ? ' is-invalid' : '' }}"
                                      name="description_en" rows="10">{{ old('description_en', $category ? $category->description_en : null)}}</textarea>
                            @if ($errors->has('description_en'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('description_en') }}</strong></span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card card-gray card-outline">
            <div class="card-body">
                <div class="form-group">
                    <label for="slug" class="col-form-label">Slug</label>
                    <input id="slug" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug', $category ? $category->slug : null) }}" required>
                    @if ($errors->has('slug'))
                        <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
                    @endif
                </div>

                <div class="form-group">
                    {!! Form::label('brands', trans('adminlte.brand.name'), ['class' => 'col-form-label']); !!}
                    {!! Form::select('brands[]', $brands, old('brands', $category ? $category->brandsList() : null),
                        ['multiple' => true, 'class'=>'form-control' . ($errors->has('brands') ? ' is-invalid' : ''), 'id' => 'brands']) !!}
                    @if ($errors->has('brands'))
                        <span class="invalid-feedback"><strong>{{ $errors->first('brands') }}</strong></span>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card card-default card-outline">
            <div class="card-body">
                <div class="form-group">
                    <label for="parent" class="col-form-label">{{ trans('adminlte.parent') }}</label>
                    <select id="parent" class="form-control{{ $errors->has('parent') ? ' is-invalid' : '' }}" name="parent">
                        <option value=""></option>
                        @foreach ($parents as $parent)
                            <option value="{{ $parent->id }}"{{ $parent->id == old('parent', $category ? $category->parent_id : null) ? ' selected' : '' }}>
                                @for ($i = 0; $i < $parent->depth; $i++) &mdash; @endfor
                                {{ $parent->name }}
                            </option>
                        @endforeach;
                    </select>
                    @if ($errors->has('parent'))
                        <span class="invalid-feedback"><strong>{{ $errors->first('parent') }}</strong></span>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card card-gray card-outline">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="photo-input" class="col-form-label">@lang('adminlte.photo.name')</label>
                            <div class="file-loading">
                                <input id="photo-input" class="file" type="file" name="photo">
                            </div>
                            @if ($errors->has('photo'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('photo') }}</strong></span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="icon-input" class="col-form-label">@lang('adminlte.icon')</label>
                            <div class="file-loading">
                                <input id="icon-input" class="file" type="file" name="icon">
                            </div>
                            @if ($errors->has('icon'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('icon') }}</strong></span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary">{{ trans('adminlte.' . ($category ? 'edit' : 'save')) }}</button>
</div>

@section($javaScriptSectionName)
    <script src="{{ asset('vendor/bootstrap-fileinput/js/plugins/piexif.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/js/plugins/sortable.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/js/plugins/purify.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/js/fileinput.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/themes/fa/theme.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/js/locales/uz.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/js/locales/ru.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap-fileinput/js/locales/LANG.js') }}"></script>
    <script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('description_uz');
        CKEDITOR.replace('description_ru');
        CKEDITOR.replace('description_en');
        $('#brands').select2();
        $('#parent').select2();

        let photoInput = $("#photo-input");
        let iconInput = $("#icon-input");
        let photoUrl = '{{ $category ? ($category->photo ? $category->photoOriginal : null) : null }}';
        let iconUrl = '{{ $category ? ($category->icon ? $category->iconOriginal : null) : null }}';

        let send = XMLHttpRequest.prototype.send, token = $('meta[name="csrf-token"]').attr('content');
        XMLHttpRequest.prototype.send = function(data) {
            this.setRequestHeader('X-CSRF-Token', token);
            return send.apply(this, arguments);
        };

        if (photoUrl) {
            photoInput.fileinput({
                initialPreview: [photoUrl],
                initialPreviewAsData: true,
                showUpload: false,
                previewFileType: 'text',
                browseOnZoneClick: true,
                overwriteInitial: true,
                deleteUrl: 'remove-photo',
                maxFileCount: 1,
                allowedFileExtensions: ['jpg', 'jpeg', 'png'],
            });
        } else {
            photoInput.fileinput({
                showUpload: false,
                previewFileType: 'text',
                browseOnZoneClick: true,
                maxFileCount: 1,
                allowedFileExtensions: ['jpg', 'jpeg', 'png'],
            });
        }

        if (iconUrl) {
            iconInput.fileinput({
                initialPreview: [iconUrl],
                initialPreviewAsData: true,
                showUpload: false,
                previewFileType: 'text',
                browseOnZoneClick: true,
                overwriteInitial: true,
                deleteUrl: 'remove-icon',
                maxFileCount: 1,
                allowedFileExtensions: ['jpg', 'jpeg', 'png'],
            });
        } else {
            iconInput.fileinput({
                showUpload: false,
                previewFileType: 'text',
                browseOnZoneClick: true,
                maxFileCount: 1,
                allowedFileExtensions: ['jpg', 'jpeg', 'png'],
            });
        }
    </script>
@endsection

resources/views/admin/categories/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#uzbek">O'zbekcha</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#russian">Ruscha</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#english">Inglizcha</a>
    </li>
</ul>

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.page')

@section('content')
    <form method="POST" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data">
        @csrf

        @include('admin.categories._nav')

        @include('admin.categories._form', ['category' => null])
    </form>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.page')

@section('content')
    <form method="POST" action="{{ route('admin.categories.update', $category) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        @include('admin.categories._nav')

        @include('admin.categories._form')
    </form>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin.page')

@section('content')
    <p><a href="{{ route('admin.categories.create') }}" class="btn btn-success">{{ trans('adminlte.category.add') }}</a></p>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>{{ trans('adminlte.name') }}</th>
            <th>Slug</th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        @foreach ($categories as $category)
            <tr>
                <td>
                    @for ($i = 0; $i < $category->depth; $i++) &mdash; @endfor
                    <a href="{{ route('admin.categories.show', $category) }}">{{ $category->name }}</a>
                </td>
                <td>{{ $category->slug }}</td>
                <td>
                    <div class="d-flex flex-row">
                        <form method="POST" action="{{ route('admin.categories.first', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-double-up"></span></button>
                        </form>
                        <form method="POST" action="{{ route('admin.categories.up', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-up"></span></button>
                        </form>
                        <form method="POST" action="{{ route('admin.categories.down', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-down"></span></button>
                        </form>
                        <form method="POST" action="{{ route('admin.categories.last', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-double-down"></span></button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
@endsection